services:

  mongodb:
    image: mongo:7
    container_name: cert-mongo

    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend

    container_name: cert-backend

    restart: always

    ports:
      - "5000:5000"

    depends_on:
      - mongodb

    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend

    container_name: cert-frontend

    restart: always

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  mongo_data: